// Code generated by Fern. DO NOT EDIT.

package client

import (
	core "github.com/fern-api/generator-cli-go/core"
	internal "github.com/fern-api/generator-cli-go/internal"
	option "github.com/fern-api/generator-cli-go/option"
)

type Client struct {
	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}
