// Code generated by Fern. DO NOT EDIT.

package generatorcli

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersFeatureConfig(t *testing.T) {
	t.Run("SetFeatures", func(t *testing.T) {
		obj := &FeatureConfig{}
		var fernTestValueFeatures []*FeatureSpec
		obj.SetFeatures(fernTestValueFeatures)
		assert.Equal(t, fernTestValueFeatures, obj.Features)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersFeatureConfig(t *testing.T) {
	t.Run("GetFeatures", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureConfig{}
		var expected []*FeatureSpec
		obj.Features = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFeatures(), "getter should return the property value")
	})

	t.Run("GetFeatures_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureConfig{}
		obj.Features = nil

		// Act & Assert
		assert.Nil(t, obj.GetFeatures(), "getter should return nil when property is nil")
	})

	t.Run("GetFeatures_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureConfig
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFeatures() // Should return zero value
	})

}

func TestSettersMarkExplicitFeatureConfig(t *testing.T) {
	t.Run("SetFeatures_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureConfig{}
		var fernTestValueFeatures []*FeatureSpec

		// Act
		obj.SetFeatures(fernTestValueFeatures)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestGettersFeatureId(t *testing.T) {
	t.Run("GetString", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureId{}
		var expected string
		obj.String = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetString(), "getter should return the property value")
	})

	t.Run("GetString_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureId
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetString() // Should return zero value
	})

	t.Run("GetStructuredFeatureId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureId{}
		var expected StructuredFeatureId
		obj.StructuredFeatureId = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStructuredFeatureId(), "getter should return the property value")
	})

	t.Run("GetStructuredFeatureId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureId
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStructuredFeatureId() // Should return zero value
	})

}

func TestSettersFeatureSpec(t *testing.T) {
	t.Run("SetId", func(t *testing.T) {
		obj := &FeatureSpec{}
		var fernTestValueId *FeatureId
		obj.SetId(fernTestValueId)
		assert.Equal(t, fernTestValueId, obj.Id)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDescription", func(t *testing.T) {
		obj := &FeatureSpec{}
		var fernTestValueDescription *string
		obj.SetDescription(fernTestValueDescription)
		assert.Equal(t, fernTestValueDescription, obj.Description)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAddendum", func(t *testing.T) {
		obj := &FeatureSpec{}
		var fernTestValueAddendum *string
		obj.SetAddendum(fernTestValueAddendum)
		assert.Equal(t, fernTestValueAddendum, obj.Addendum)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAdvanced", func(t *testing.T) {
		obj := &FeatureSpec{}
		var fernTestValueAdvanced *bool
		obj.SetAdvanced(fernTestValueAdvanced)
		assert.Equal(t, fernTestValueAdvanced, obj.Advanced)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersFeatureSpec(t *testing.T) {
	t.Run("GetId", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		var expected *FeatureId
		obj.Id = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetId(), "getter should return the property value")
	})

	t.Run("GetId_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		obj.Id = nil

		// Act & Assert
		assert.Nil(t, obj.GetId(), "getter should return nil when property is nil")
	})

	t.Run("GetId_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureSpec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetId() // Should return zero value
	})

	t.Run("GetDescription", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		var expected *string
		obj.Description = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDescription(), "getter should return the property value")
	})

	t.Run("GetDescription_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		obj.Description = nil

		// Act & Assert
		assert.Nil(t, obj.GetDescription(), "getter should return nil when property is nil")
	})

	t.Run("GetDescription_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureSpec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDescription() // Should return zero value
	})

	t.Run("GetAddendum", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		var expected *string
		obj.Addendum = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAddendum(), "getter should return the property value")
	})

	t.Run("GetAddendum_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		obj.Addendum = nil

		// Act & Assert
		assert.Nil(t, obj.GetAddendum(), "getter should return nil when property is nil")
	})

	t.Run("GetAddendum_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureSpec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAddendum() // Should return zero value
	})

	t.Run("GetAdvanced", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		var expected *bool
		obj.Advanced = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAdvanced(), "getter should return the property value")
	})

	t.Run("GetAdvanced_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		obj.Advanced = nil

		// Act & Assert
		assert.Nil(t, obj.GetAdvanced(), "getter should return nil when property is nil")
	})

	t.Run("GetAdvanced_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureSpec
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAdvanced() // Should return zero value
	})

}

func TestSettersMarkExplicitFeatureSpec(t *testing.T) {
	t.Run("SetId_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		var fernTestValueId *FeatureId

		// Act
		obj.SetId(fernTestValueId)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDescription_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		var fernTestValueDescription *string

		// Act
		obj.SetDescription(fernTestValueDescription)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAddendum_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		var fernTestValueAddendum *string

		// Act
		obj.SetAddendum(fernTestValueAddendum)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAdvanced_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}
		var fernTestValueAdvanced *bool

		// Act
		obj.SetAdvanced(fernTestValueAdvanced)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingFeatureConfig(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureConfig{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled FeatureConfig
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj FeatureConfig
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj FeatureConfig
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingFeatureSpec(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &FeatureSpec{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled FeatureSpec
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj FeatureSpec
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj FeatureSpec
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringFeatureConfig(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &FeatureConfig{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureConfig
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringFeatureSpec(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &FeatureSpec{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureSpec
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumStructuredFeatureId(t *testing.T) {
	t.Run("NewFromString_AUTHENTICATION", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("AUTHENTICATION")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("AUTHENTICATION"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_ERRORS", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("ERRORS")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("ERRORS"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_USAGE", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("USAGE")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("USAGE"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_PAGINATION", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("PAGINATION")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("PAGINATION"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_RETRIES", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("RETRIES")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("RETRIES"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_REQUEST_OPTIONS", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("REQUEST_OPTIONS")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("REQUEST_OPTIONS"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_STREAMING", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("STREAMING")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("STREAMING"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_TIMEOUTS", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("TIMEOUTS")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("TIMEOUTS"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_CUSTOM_CLIENT", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("CUSTOM_CLIENT")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("CUSTOM_CLIENT"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_CONTRIBUTING", func(t *testing.T) {
		t.Parallel()
		val, err := NewStructuredFeatureIdFromString("CONTRIBUTING")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, StructuredFeatureId("CONTRIBUTING"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewStructuredFeatureIdFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewStructuredFeatureIdFromString("AUTHENTICATION")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesFeatureConfig(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &FeatureConfig{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureConfig
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesFeatureSpec(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &FeatureSpec{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *FeatureSpec
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
