// Code generated by Fern. DO NOT EDIT.

package generatorcli

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-api/generator-cli-go/internal"
	big "math/big"
)

// The configuration used to interact with a GitHub repository.
var (
	gitHubConfigFieldSourceDirectory = big.NewInt(1 << 0)
	gitHubConfigFieldUri             = big.NewInt(1 << 1)
	gitHubConfigFieldToken           = big.NewInt(1 << 2)
	gitHubConfigFieldBranch          = big.NewInt(1 << 3)
)

type GitHubConfig struct {
	// The directory from which to read the contents of the GitHub repository.
	SourceDirectory string `json:"sourceDirectory" url:"sourceDirectory"`
	// The URI of the GitHub repository.
	Uri string `json:"uri" url:"uri"`
	// The token used to access the GitHub repository.
	Token string `json:"token" url:"token"`
	// The branch to use when interacting with the GitHub repository.
	Branch *string `json:"branch,omitempty" url:"branch,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GitHubConfig) GetSourceDirectory() string {
	if g == nil {
		return ""
	}
	return g.SourceDirectory
}

func (g *GitHubConfig) GetUri() string {
	if g == nil {
		return ""
	}
	return g.Uri
}

func (g *GitHubConfig) GetToken() string {
	if g == nil {
		return ""
	}
	return g.Token
}

func (g *GitHubConfig) GetBranch() *string {
	if g == nil {
		return nil
	}
	return g.Branch
}

func (g *GitHubConfig) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GitHubConfig) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetSourceDirectory sets the SourceDirectory field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GitHubConfig) SetSourceDirectory(sourceDirectory string) {
	g.SourceDirectory = sourceDirectory
	g.require(gitHubConfigFieldSourceDirectory)
}

// SetUri sets the Uri field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GitHubConfig) SetUri(uri string) {
	g.Uri = uri
	g.require(gitHubConfigFieldUri)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GitHubConfig) SetToken(token string) {
	g.Token = token
	g.require(gitHubConfigFieldToken)
}

// SetBranch sets the Branch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GitHubConfig) SetBranch(branch *string) {
	g.Branch = branch
	g.require(gitHubConfigFieldBranch)
}

func (g *GitHubConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler GitHubConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GitHubConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GitHubConfig) MarshalJSON() ([]byte, error) {
	type embed GitHubConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GitHubConfig) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
