// Code generated by Fern. DO NOT EDIT.

package generatorcli

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/fern-api/generator-cli-go/internal"
	big "math/big"
)

var (
	cargoPublishInfoFieldPackageName = big.NewInt(1 << 0)
	cargoPublishInfoFieldVersion     = big.NewInt(1 << 1)
)

type CargoPublishInfo struct {
	PackageName string `json:"packageName" url:"packageName"`
	Version     string `json:"version" url:"version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CargoPublishInfo) GetPackageName() string {
	if c == nil {
		return ""
	}
	return c.PackageName
}

func (c *CargoPublishInfo) GetVersion() string {
	if c == nil {
		return ""
	}
	return c.Version
}

func (c *CargoPublishInfo) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CargoPublishInfo) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPackageName sets the PackageName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CargoPublishInfo) SetPackageName(packageName string) {
	c.PackageName = packageName
	c.require(cargoPublishInfoFieldPackageName)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CargoPublishInfo) SetVersion(version string) {
	c.Version = version
	c.require(cargoPublishInfoFieldVersion)
}

func (c *CargoPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler CargoPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CargoPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CargoPublishInfo) MarshalJSON() ([]byte, error) {
	type embed CargoPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CargoPublishInfo) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// A code snippet that will be wrapped in a code fence with the specified language.
// If no language is specified, the generator's language will be used.
var (
	codeSnippetFieldContent  = big.NewInt(1 << 0)
	codeSnippetFieldLanguage = big.NewInt(1 << 1)
)

type CodeSnippet struct {
	Content string `json:"content" url:"content"`
	// The language for the code fence. If not specified, the generator's language will be used.
	Language *string `json:"language,omitempty" url:"language,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	type_          string

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CodeSnippet) GetContent() string {
	if c == nil {
		return ""
	}
	return c.Content
}

func (c *CodeSnippet) GetLanguage() *string {
	if c == nil {
		return nil
	}
	return c.Language
}

func (c *CodeSnippet) Type() string {
	return c.type_
}

func (c *CodeSnippet) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CodeSnippet) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeSnippet) SetContent(content string) {
	c.Content = content
	c.require(codeSnippetFieldContent)
}

// SetLanguage sets the Language field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeSnippet) SetLanguage(language *string) {
	c.Language = language
	c.require(codeSnippetFieldLanguage)
}

func (c *CodeSnippet) UnmarshalJSON(data []byte) error {
	type embed CodeSnippet
	var unmarshaler = struct {
		embed
		Type string `json:"type"`
	}{
		embed: embed(*c),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*c = CodeSnippet(unmarshaler.embed)
	if unmarshaler.Type != "code" {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", c, "code", unmarshaler.Type)
	}
	c.type_ = unmarshaler.Type
	extraProperties, err := internal.ExtractExtraProperties(data, *c, "type")
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CodeSnippet) MarshalJSON() ([]byte, error) {
	type embed CodeSnippet
	var marshaler = struct {
		embed
		Type string `json:"type"`
	}{
		embed: embed(*c),
		Type:  "code",
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CodeSnippet) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	composerPublishInfoFieldPackageName = big.NewInt(1 << 0)
)

type ComposerPublishInfo struct {
	PackageName string `json:"packageName" url:"packageName"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *ComposerPublishInfo) GetPackageName() string {
	if c == nil {
		return ""
	}
	return c.PackageName
}

func (c *ComposerPublishInfo) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *ComposerPublishInfo) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPackageName sets the PackageName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ComposerPublishInfo) SetPackageName(packageName string) {
	c.PackageName = packageName
	c.require(composerPublishInfoFieldPackageName)
}

func (c *ComposerPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler ComposerPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = ComposerPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *ComposerPublishInfo) MarshalJSON() ([]byte, error) {
	type embed ComposerPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *ComposerPublishInfo) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	csharpInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type CsharpInfo struct {
	PublishInfo *NugetPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CsharpInfo) GetPublishInfo() *NugetPublishInfo {
	if c == nil {
		return nil
	}
	return c.PublishInfo
}

func (c *CsharpInfo) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CsharpInfo) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CsharpInfo) SetPublishInfo(publishInfo *NugetPublishInfo) {
	c.PublishInfo = publishInfo
	c.require(csharpInfoFieldPublishInfo)
}

func (c *CsharpInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler CsharpInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CsharpInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CsharpInfo) MarshalJSON() ([]byte, error) {
	type embed CsharpInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CsharpInfo) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	customSectionFieldName     = big.NewInt(1 << 0)
	customSectionFieldLanguage = big.NewInt(1 << 1)
	customSectionFieldContent  = big.NewInt(1 << 2)
)

type CustomSection struct {
	Name     string   `json:"name" url:"name"`
	Language Language `json:"language" url:"language"`
	Content  string   `json:"content" url:"content"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CustomSection) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CustomSection) GetLanguage() Language {
	if c == nil {
		return ""
	}
	return c.Language
}

func (c *CustomSection) GetContent() string {
	if c == nil {
		return ""
	}
	return c.Content
}

func (c *CustomSection) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CustomSection) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSection) SetName(name string) {
	c.Name = name
	c.require(customSectionFieldName)
}

// SetLanguage sets the Language field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSection) SetLanguage(language Language) {
	c.Language = language
	c.require(customSectionFieldLanguage)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CustomSection) SetContent(content string) {
	c.Content = content
	c.require(customSectionFieldContent)
}

func (c *CustomSection) UnmarshalJSON(data []byte) error {
	type unmarshaler CustomSection
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CustomSection(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CustomSection) MarshalJSON() ([]byte, error) {
	type embed CustomSection
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CustomSection) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Controls the verbosity of usage examples in README generation
type ExampleStyle string

const (
	ExampleStyleMinimal       ExampleStyle = "minimal"
	ExampleStyleComprehensive ExampleStyle = "comprehensive"
)

func NewExampleStyleFromString(s string) (ExampleStyle, error) {
	switch s {
	case "minimal":
		return ExampleStyleMinimal, nil
	case "comprehensive":
		return ExampleStyleComprehensive, nil
	}
	var t ExampleStyle
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e ExampleStyle) Ptr() *ExampleStyle {
	return &e
}

var (
	githubRemoteFieldRepoUrl           = big.NewInt(1 << 0)
	githubRemoteFieldInstallationToken = big.NewInt(1 << 1)
	githubRemoteFieldBranch            = big.NewInt(1 << 2)
)

type GithubRemote struct {
	// A full repo url (i.e. https://github.com/fern-api/fern)
	RepoUrl string `json:"repoUrl" url:"repoUrl"`
	// The token used to clone the GitHub repository.
	InstallationToken string `json:"installationToken" url:"installationToken"`
	// The branch to clone from. If not specified, the default branch will be used.
	Branch *string `json:"branch,omitempty" url:"branch,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GithubRemote) GetRepoUrl() string {
	if g == nil {
		return ""
	}
	return g.RepoUrl
}

func (g *GithubRemote) GetInstallationToken() string {
	if g == nil {
		return ""
	}
	return g.InstallationToken
}

func (g *GithubRemote) GetBranch() *string {
	if g == nil {
		return nil
	}
	return g.Branch
}

func (g *GithubRemote) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GithubRemote) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetRepoUrl sets the RepoUrl field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubRemote) SetRepoUrl(repoUrl string) {
	g.RepoUrl = repoUrl
	g.require(githubRemoteFieldRepoUrl)
}

// SetInstallationToken sets the InstallationToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubRemote) SetInstallationToken(installationToken string) {
	g.InstallationToken = installationToken
	g.require(githubRemoteFieldInstallationToken)
}

// SetBranch sets the Branch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GithubRemote) SetBranch(branch *string) {
	g.Branch = branch
	g.require(githubRemoteFieldBranch)
}

func (g *GithubRemote) UnmarshalJSON(data []byte) error {
	type unmarshaler GithubRemote
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GithubRemote(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GithubRemote) MarshalJSON() ([]byte, error) {
	type embed GithubRemote
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GithubRemote) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	goInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type GoInfo struct {
	PublishInfo *GoPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GoInfo) GetPublishInfo() *GoPublishInfo {
	if g == nil {
		return nil
	}
	return g.PublishInfo
}

func (g *GoInfo) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GoInfo) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoInfo) SetPublishInfo(publishInfo *GoPublishInfo) {
	g.PublishInfo = publishInfo
	g.require(goInfoFieldPublishInfo)
}

func (g *GoInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler GoInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GoInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GoInfo) MarshalJSON() ([]byte, error) {
	type embed GoInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GoInfo) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	goPublishInfoFieldOwner   = big.NewInt(1 << 0)
	goPublishInfoFieldRepo    = big.NewInt(1 << 1)
	goPublishInfoFieldVersion = big.NewInt(1 << 2)
)

type GoPublishInfo struct {
	Owner   string `json:"owner" url:"owner"`
	Repo    string `json:"repo" url:"repo"`
	Version string `json:"version" url:"version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GoPublishInfo) GetOwner() string {
	if g == nil {
		return ""
	}
	return g.Owner
}

func (g *GoPublishInfo) GetRepo() string {
	if g == nil {
		return ""
	}
	return g.Repo
}

func (g *GoPublishInfo) GetVersion() string {
	if g == nil {
		return ""
	}
	return g.Version
}

func (g *GoPublishInfo) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GoPublishInfo) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetOwner sets the Owner field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoPublishInfo) SetOwner(owner string) {
	g.Owner = owner
	g.require(goPublishInfoFieldOwner)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoPublishInfo) SetRepo(repo string) {
	g.Repo = repo
	g.require(goPublishInfoFieldRepo)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GoPublishInfo) SetVersion(version string) {
	g.Version = version
	g.require(goPublishInfoFieldVersion)
}

func (g *GoPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler GoPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GoPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GoPublishInfo) MarshalJSON() ([]byte, error) {
	type embed GoPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GoPublishInfo) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	javaInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type JavaInfo struct {
	PublishInfo *MavenPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (j *JavaInfo) GetPublishInfo() *MavenPublishInfo {
	if j == nil {
		return nil
	}
	return j.PublishInfo
}

func (j *JavaInfo) GetExtraProperties() map[string]interface{} {
	if j == nil {
		return nil
	}
	return j.extraProperties
}

func (j *JavaInfo) require(field *big.Int) {
	if j.explicitFields == nil {
		j.explicitFields = big.NewInt(0)
	}
	j.explicitFields.Or(j.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (j *JavaInfo) SetPublishInfo(publishInfo *MavenPublishInfo) {
	j.PublishInfo = publishInfo
	j.require(javaInfoFieldPublishInfo)
}

func (j *JavaInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler JavaInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*j = JavaInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *j)
	if err != nil {
		return err
	}
	j.extraProperties = extraProperties
	j.rawJSON = json.RawMessage(data)
	return nil
}

func (j *JavaInfo) MarshalJSON() ([]byte, error) {
	type embed JavaInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*j),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, j.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (j *JavaInfo) String() string {
	if j == nil {
		return "<nil>"
	}
	if len(j.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(j.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(j); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", j)
}

// The language and its associated publish information (if any).
// This is used to generate badges, the installation guide, and determine what language to
// use when surrounding the snippets in a code block.
type LanguageInfo struct {
	Type       string
	Typescript *TypescriptInfo
	Python     *PythonInfo
	Go         *GoInfo
	Java       *JavaInfo
	Ruby       *RubyInfo
	Csharp     *CsharpInfo
	Php        *PhpInfo
	Rust       *RustInfo
	Swift      *SwiftInfo
}

func (l *LanguageInfo) GetType() string {
	if l == nil {
		return ""
	}
	return l.Type
}

func (l *LanguageInfo) GetTypescript() *TypescriptInfo {
	if l == nil {
		return nil
	}
	return l.Typescript
}

func (l *LanguageInfo) GetPython() *PythonInfo {
	if l == nil {
		return nil
	}
	return l.Python
}

func (l *LanguageInfo) GetGo() *GoInfo {
	if l == nil {
		return nil
	}
	return l.Go
}

func (l *LanguageInfo) GetJava() *JavaInfo {
	if l == nil {
		return nil
	}
	return l.Java
}

func (l *LanguageInfo) GetRuby() *RubyInfo {
	if l == nil {
		return nil
	}
	return l.Ruby
}

func (l *LanguageInfo) GetCsharp() *CsharpInfo {
	if l == nil {
		return nil
	}
	return l.Csharp
}

func (l *LanguageInfo) GetPhp() *PhpInfo {
	if l == nil {
		return nil
	}
	return l.Php
}

func (l *LanguageInfo) GetRust() *RustInfo {
	if l == nil {
		return nil
	}
	return l.Rust
}

func (l *LanguageInfo) GetSwift() *SwiftInfo {
	if l == nil {
		return nil
	}
	return l.Swift
}

func (l *LanguageInfo) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	l.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", l)
	}
	switch unmarshaler.Type {
	case "typescript":
		value := new(TypescriptInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Typescript = value
	case "python":
		value := new(PythonInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Python = value
	case "go":
		value := new(GoInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Go = value
	case "java":
		value := new(JavaInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Java = value
	case "ruby":
		value := new(RubyInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Ruby = value
	case "csharp":
		value := new(CsharpInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Csharp = value
	case "php":
		value := new(PhpInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Php = value
	case "rust":
		value := new(RustInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Rust = value
	case "swift":
		value := new(SwiftInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Swift = value
	}
	return nil
}

func (l LanguageInfo) MarshalJSON() ([]byte, error) {
	if err := l.validate(); err != nil {
		return nil, err
	}
	if l.Typescript != nil {
		return internal.MarshalJSONWithExtraProperty(l.Typescript, "type", "typescript")
	}
	if l.Python != nil {
		return internal.MarshalJSONWithExtraProperty(l.Python, "type", "python")
	}
	if l.Go != nil {
		return internal.MarshalJSONWithExtraProperty(l.Go, "type", "go")
	}
	if l.Java != nil {
		return internal.MarshalJSONWithExtraProperty(l.Java, "type", "java")
	}
	if l.Ruby != nil {
		return internal.MarshalJSONWithExtraProperty(l.Ruby, "type", "ruby")
	}
	if l.Csharp != nil {
		return internal.MarshalJSONWithExtraProperty(l.Csharp, "type", "csharp")
	}
	if l.Php != nil {
		return internal.MarshalJSONWithExtraProperty(l.Php, "type", "php")
	}
	if l.Rust != nil {
		return internal.MarshalJSONWithExtraProperty(l.Rust, "type", "rust")
	}
	if l.Swift != nil {
		return internal.MarshalJSONWithExtraProperty(l.Swift, "type", "swift")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", l)
}

type LanguageInfoVisitor interface {
	VisitTypescript(*TypescriptInfo) error
	VisitPython(*PythonInfo) error
	VisitGo(*GoInfo) error
	VisitJava(*JavaInfo) error
	VisitRuby(*RubyInfo) error
	VisitCsharp(*CsharpInfo) error
	VisitPhp(*PhpInfo) error
	VisitRust(*RustInfo) error
	VisitSwift(*SwiftInfo) error
}

func (l *LanguageInfo) Accept(visitor LanguageInfoVisitor) error {
	if l.Typescript != nil {
		return visitor.VisitTypescript(l.Typescript)
	}
	if l.Python != nil {
		return visitor.VisitPython(l.Python)
	}
	if l.Go != nil {
		return visitor.VisitGo(l.Go)
	}
	if l.Java != nil {
		return visitor.VisitJava(l.Java)
	}
	if l.Ruby != nil {
		return visitor.VisitRuby(l.Ruby)
	}
	if l.Csharp != nil {
		return visitor.VisitCsharp(l.Csharp)
	}
	if l.Php != nil {
		return visitor.VisitPhp(l.Php)
	}
	if l.Rust != nil {
		return visitor.VisitRust(l.Rust)
	}
	if l.Swift != nil {
		return visitor.VisitSwift(l.Swift)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", l)
}

func (l *LanguageInfo) validate() error {
	if l == nil {
		return fmt.Errorf("type %T is nil", l)
	}
	var fields []string
	if l.Typescript != nil {
		fields = append(fields, "typescript")
	}
	if l.Python != nil {
		fields = append(fields, "python")
	}
	if l.Go != nil {
		fields = append(fields, "go")
	}
	if l.Java != nil {
		fields = append(fields, "java")
	}
	if l.Ruby != nil {
		fields = append(fields, "ruby")
	}
	if l.Csharp != nil {
		fields = append(fields, "csharp")
	}
	if l.Php != nil {
		fields = append(fields, "php")
	}
	if l.Rust != nil {
		fields = append(fields, "rust")
	}
	if l.Swift != nil {
		fields = append(fields, "swift")
	}
	if len(fields) == 0 {
		if l.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", l, l.Type)
		}
		return fmt.Errorf("type %T is empty", l)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", l, fields)
	}
	if l.Type != "" {
		field := fields[0]
		if l.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				l,
				l.Type,
				l,
			)
		}
	}
	return nil
}

// A markdown snippet that will be rendered as-is without code fences.
var (
	markdownSnippetFieldContent = big.NewInt(1 << 0)
)

type MarkdownSnippet struct {
	Content string `json:"content" url:"content"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
	type_          string

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MarkdownSnippet) GetContent() string {
	if m == nil {
		return ""
	}
	return m.Content
}

func (m *MarkdownSnippet) Type() string {
	return m.type_
}

func (m *MarkdownSnippet) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MarkdownSnippet) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetContent sets the Content field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MarkdownSnippet) SetContent(content string) {
	m.Content = content
	m.require(markdownSnippetFieldContent)
}

func (m *MarkdownSnippet) UnmarshalJSON(data []byte) error {
	type embed MarkdownSnippet
	var unmarshaler = struct {
		embed
		Type string `json:"type"`
	}{
		embed: embed(*m),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*m = MarkdownSnippet(unmarshaler.embed)
	if unmarshaler.Type != "markdown" {
		return fmt.Errorf("unexpected value for literal on type %T; expected %v got %v", m, "markdown", unmarshaler.Type)
	}
	m.type_ = unmarshaler.Type
	extraProperties, err := internal.ExtractExtraProperties(data, *m, "type")
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MarkdownSnippet) MarshalJSON() ([]byte, error) {
	type embed MarkdownSnippet
	var marshaler = struct {
		embed
		Type string `json:"type"`
	}{
		embed: embed(*m),
		Type:  "markdown",
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MarkdownSnippet) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	mavenPublishInfoFieldArtifact = big.NewInt(1 << 0)
	mavenPublishInfoFieldGroup    = big.NewInt(1 << 1)
	mavenPublishInfoFieldVersion  = big.NewInt(1 << 2)
)

type MavenPublishInfo struct {
	Artifact string `json:"artifact" url:"artifact"`
	Group    string `json:"group" url:"group"`
	Version  string `json:"version" url:"version"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MavenPublishInfo) GetArtifact() string {
	if m == nil {
		return ""
	}
	return m.Artifact
}

func (m *MavenPublishInfo) GetGroup() string {
	if m == nil {
		return ""
	}
	return m.Group
}

func (m *MavenPublishInfo) GetVersion() string {
	if m == nil {
		return ""
	}
	return m.Version
}

func (m *MavenPublishInfo) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MavenPublishInfo) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetArtifact sets the Artifact field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MavenPublishInfo) SetArtifact(artifact string) {
	m.Artifact = artifact
	m.require(mavenPublishInfoFieldArtifact)
}

// SetGroup sets the Group field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MavenPublishInfo) SetGroup(group string) {
	m.Group = group
	m.require(mavenPublishInfoFieldGroup)
}

// SetVersion sets the Version field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MavenPublishInfo) SetVersion(version string) {
	m.Version = version
	m.require(mavenPublishInfoFieldVersion)
}

func (m *MavenPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler MavenPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MavenPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MavenPublishInfo) MarshalJSON() ([]byte, error) {
	type embed MavenPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MavenPublishInfo) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	npmPublishInfoFieldPackageName = big.NewInt(1 << 0)
)

type NpmPublishInfo struct {
	PackageName string `json:"packageName" url:"packageName"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NpmPublishInfo) GetPackageName() string {
	if n == nil {
		return ""
	}
	return n.PackageName
}

func (n *NpmPublishInfo) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NpmPublishInfo) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetPackageName sets the PackageName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NpmPublishInfo) SetPackageName(packageName string) {
	n.PackageName = packageName
	n.require(npmPublishInfoFieldPackageName)
}

func (n *NpmPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler NpmPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NpmPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NpmPublishInfo) MarshalJSON() ([]byte, error) {
	type embed NpmPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NpmPublishInfo) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	nugetPublishInfoFieldPackageName = big.NewInt(1 << 0)
)

type NugetPublishInfo struct {
	PackageName string `json:"packageName" url:"packageName"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (n *NugetPublishInfo) GetPackageName() string {
	if n == nil {
		return ""
	}
	return n.PackageName
}

func (n *NugetPublishInfo) GetExtraProperties() map[string]interface{} {
	if n == nil {
		return nil
	}
	return n.extraProperties
}

func (n *NugetPublishInfo) require(field *big.Int) {
	if n.explicitFields == nil {
		n.explicitFields = big.NewInt(0)
	}
	n.explicitFields.Or(n.explicitFields, field)
}

// SetPackageName sets the PackageName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (n *NugetPublishInfo) SetPackageName(packageName string) {
	n.PackageName = packageName
	n.require(nugetPublishInfoFieldPackageName)
}

func (n *NugetPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler NugetPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*n = NugetPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *n)
	if err != nil {
		return err
	}
	n.extraProperties = extraProperties
	n.rawJSON = json.RawMessage(data)
	return nil
}

func (n *NugetPublishInfo) MarshalJSON() ([]byte, error) {
	type embed NugetPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*n),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, n.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (n *NugetPublishInfo) String() string {
	if n == nil {
		return "<nil>"
	}
	if len(n.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(n.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

var (
	phpInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type PhpInfo struct {
	PublishInfo *ComposerPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PhpInfo) GetPublishInfo() *ComposerPublishInfo {
	if p == nil {
		return nil
	}
	return p.PublishInfo
}

func (p *PhpInfo) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PhpInfo) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PhpInfo) SetPublishInfo(publishInfo *ComposerPublishInfo) {
	p.PublishInfo = publishInfo
	p.require(phpInfoFieldPublishInfo)
}

func (p *PhpInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler PhpInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PhpInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PhpInfo) MarshalJSON() ([]byte, error) {
	type embed PhpInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PhpInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	pypiPublishInfoFieldPackageName = big.NewInt(1 << 0)
)

type PypiPublishInfo struct {
	PackageName string `json:"packageName" url:"packageName"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PypiPublishInfo) GetPackageName() string {
	if p == nil {
		return ""
	}
	return p.PackageName
}

func (p *PypiPublishInfo) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PypiPublishInfo) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPackageName sets the PackageName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PypiPublishInfo) SetPackageName(packageName string) {
	p.PackageName = packageName
	p.require(pypiPublishInfoFieldPackageName)
}

func (p *PypiPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler PypiPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PypiPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PypiPublishInfo) MarshalJSON() ([]byte, error) {
	type embed PypiPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PypiPublishInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	pythonInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type PythonInfo struct {
	PublishInfo *PypiPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PythonInfo) GetPublishInfo() *PypiPublishInfo {
	if p == nil {
		return nil
	}
	return p.PublishInfo
}

func (p *PythonInfo) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PythonInfo) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PythonInfo) SetPublishInfo(publishInfo *PypiPublishInfo) {
	p.PublishInfo = publishInfo
	p.require(pythonInfoFieldPublishInfo)
}

func (p *PythonInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler PythonInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PythonInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PythonInfo) MarshalJSON() ([]byte, error) {
	type embed PythonInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PythonInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// The configuration used to generate a README.md file.
// The information described here is a combination of user-defined information
// (i.e. specified in the generators.yml), and dynamically generated information
// that comes from each generator (i.e. features, requirements, and more).
var (
	readmeConfigFieldRemote                = big.NewInt(1 << 0)
	readmeConfigFieldLanguage              = big.NewInt(1 << 1)
	readmeConfigFieldOrganization          = big.NewInt(1 << 2)
	readmeConfigFieldApiName               = big.NewInt(1 << 3)
	readmeConfigFieldBannerLink            = big.NewInt(1 << 4)
	readmeConfigFieldIntroduction          = big.NewInt(1 << 5)
	readmeConfigFieldApiReferenceLink      = big.NewInt(1 << 6)
	readmeConfigFieldReferenceMarkdownPath = big.NewInt(1 << 7)
	readmeConfigFieldRequirements          = big.NewInt(1 << 8)
	readmeConfigFieldDisabledFeatures      = big.NewInt(1 << 9)
	readmeConfigFieldWhiteLabel            = big.NewInt(1 << 10)
	readmeConfigFieldCustomSections        = big.NewInt(1 << 11)
	readmeConfigFieldFeatures              = big.NewInt(1 << 12)
	readmeConfigFieldExampleStyle          = big.NewInt(1 << 13)
)

type ReadmeConfig struct {
	// If specified, the original README.md will be fetched from this remote (if it exists).
	Remote                *Remote          `json:"remote,omitempty" url:"remote,omitempty"`
	Language              *LanguageInfo    `json:"language" url:"language"`
	Organization          string           `json:"organization" url:"organization"`
	ApiName               *string          `json:"apiName,omitempty" url:"apiName,omitempty"`
	BannerLink            *string          `json:"bannerLink,omitempty" url:"bannerLink,omitempty"`
	Introduction          *string          `json:"introduction,omitempty" url:"introduction,omitempty"`
	ApiReferenceLink      *string          `json:"apiReferenceLink,omitempty" url:"apiReferenceLink,omitempty"`
	ReferenceMarkdownPath *string          `json:"referenceMarkdownPath,omitempty" url:"referenceMarkdownPath,omitempty"`
	Requirements          []string         `json:"requirements,omitempty" url:"requirements,omitempty"`
	DisabledFeatures      []*FeatureId     `json:"disabledFeatures,omitempty" url:"disabledFeatures,omitempty"`
	WhiteLabel            *bool            `json:"whiteLabel,omitempty" url:"whiteLabel,omitempty"`
	CustomSections        []*CustomSection `json:"customSections,omitempty" url:"customSections,omitempty"`
	// Specifies the list of features supported by a specific generator.
	// The features are rendered in the order they're specified.
	Features []*ReadmeFeature `json:"features,omitempty" url:"features,omitempty"`
	// Controls whether usage examples show only required parameters (minimal) or all parameters (comprehensive). Defaults to comprehensive.
	ExampleStyle *ExampleStyle `json:"exampleStyle,omitempty" url:"exampleStyle,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReadmeConfig) GetRemote() *Remote {
	if r == nil {
		return nil
	}
	return r.Remote
}

func (r *ReadmeConfig) GetLanguage() *LanguageInfo {
	if r == nil {
		return nil
	}
	return r.Language
}

func (r *ReadmeConfig) GetOrganization() string {
	if r == nil {
		return ""
	}
	return r.Organization
}

func (r *ReadmeConfig) GetApiName() *string {
	if r == nil {
		return nil
	}
	return r.ApiName
}

func (r *ReadmeConfig) GetBannerLink() *string {
	if r == nil {
		return nil
	}
	return r.BannerLink
}

func (r *ReadmeConfig) GetIntroduction() *string {
	if r == nil {
		return nil
	}
	return r.Introduction
}

func (r *ReadmeConfig) GetApiReferenceLink() *string {
	if r == nil {
		return nil
	}
	return r.ApiReferenceLink
}

func (r *ReadmeConfig) GetReferenceMarkdownPath() *string {
	if r == nil {
		return nil
	}
	return r.ReferenceMarkdownPath
}

func (r *ReadmeConfig) GetRequirements() []string {
	if r == nil {
		return nil
	}
	return r.Requirements
}

func (r *ReadmeConfig) GetDisabledFeatures() []*FeatureId {
	if r == nil {
		return nil
	}
	return r.DisabledFeatures
}

func (r *ReadmeConfig) GetWhiteLabel() *bool {
	if r == nil {
		return nil
	}
	return r.WhiteLabel
}

func (r *ReadmeConfig) GetCustomSections() []*CustomSection {
	if r == nil {
		return nil
	}
	return r.CustomSections
}

func (r *ReadmeConfig) GetFeatures() []*ReadmeFeature {
	if r == nil {
		return nil
	}
	return r.Features
}

func (r *ReadmeConfig) GetExampleStyle() *ExampleStyle {
	if r == nil {
		return nil
	}
	return r.ExampleStyle
}

func (r *ReadmeConfig) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReadmeConfig) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetRemote sets the Remote field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetRemote(remote *Remote) {
	r.Remote = remote
	r.require(readmeConfigFieldRemote)
}

// SetLanguage sets the Language field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetLanguage(language *LanguageInfo) {
	r.Language = language
	r.require(readmeConfigFieldLanguage)
}

// SetOrganization sets the Organization field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetOrganization(organization string) {
	r.Organization = organization
	r.require(readmeConfigFieldOrganization)
}

// SetApiName sets the ApiName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetApiName(apiName *string) {
	r.ApiName = apiName
	r.require(readmeConfigFieldApiName)
}

// SetBannerLink sets the BannerLink field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetBannerLink(bannerLink *string) {
	r.BannerLink = bannerLink
	r.require(readmeConfigFieldBannerLink)
}

// SetIntroduction sets the Introduction field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetIntroduction(introduction *string) {
	r.Introduction = introduction
	r.require(readmeConfigFieldIntroduction)
}

// SetApiReferenceLink sets the ApiReferenceLink field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetApiReferenceLink(apiReferenceLink *string) {
	r.ApiReferenceLink = apiReferenceLink
	r.require(readmeConfigFieldApiReferenceLink)
}

// SetReferenceMarkdownPath sets the ReferenceMarkdownPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetReferenceMarkdownPath(referenceMarkdownPath *string) {
	r.ReferenceMarkdownPath = referenceMarkdownPath
	r.require(readmeConfigFieldReferenceMarkdownPath)
}

// SetRequirements sets the Requirements field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetRequirements(requirements []string) {
	r.Requirements = requirements
	r.require(readmeConfigFieldRequirements)
}

// SetDisabledFeatures sets the DisabledFeatures field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetDisabledFeatures(disabledFeatures []*FeatureId) {
	r.DisabledFeatures = disabledFeatures
	r.require(readmeConfigFieldDisabledFeatures)
}

// SetWhiteLabel sets the WhiteLabel field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetWhiteLabel(whiteLabel *bool) {
	r.WhiteLabel = whiteLabel
	r.require(readmeConfigFieldWhiteLabel)
}

// SetCustomSections sets the CustomSections field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetCustomSections(customSections []*CustomSection) {
	r.CustomSections = customSections
	r.require(readmeConfigFieldCustomSections)
}

// SetFeatures sets the Features field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetFeatures(features []*ReadmeFeature) {
	r.Features = features
	r.require(readmeConfigFieldFeatures)
}

// SetExampleStyle sets the ExampleStyle field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeConfig) SetExampleStyle(exampleStyle *ExampleStyle) {
	r.ExampleStyle = exampleStyle
	r.require(readmeConfigFieldExampleStyle)
}

func (r *ReadmeConfig) UnmarshalJSON(data []byte) error {
	type unmarshaler ReadmeConfig
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReadmeConfig(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReadmeConfig) MarshalJSON() ([]byte, error) {
	type embed ReadmeConfig
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReadmeConfig) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// A single feature supported by a generator (e.g. PAGINATION).
var (
	readmeFeatureFieldId                  = big.NewInt(1 << 0)
	readmeFeatureFieldDescription         = big.NewInt(1 << 1)
	readmeFeatureFieldAddendum            = big.NewInt(1 << 2)
	readmeFeatureFieldAdvanced            = big.NewInt(1 << 3)
	readmeFeatureFieldSnippets            = big.NewInt(1 << 4)
	readmeFeatureFieldSnippetsAreOptional = big.NewInt(1 << 5)
)

type ReadmeFeature struct {
	Id          *FeatureId `json:"id" url:"id"`
	Description *string    `json:"description,omitempty" url:"description,omitempty"`
	Addendum    *string    `json:"addendum,omitempty" url:"addendum,omitempty"`
	Advanced    *bool      `json:"advanced,omitempty" url:"advanced,omitempty"`
	Snippets    []*Snippet `json:"snippets,omitempty" url:"snippets,omitempty"`
	// If true, the feature block should be rendered even if we don't receive a snippet for it.
	// This is useful for features that are always supported, but might not require a snippet
	// to explain.
	SnippetsAreOptional bool `json:"snippetsAreOptional" url:"snippetsAreOptional"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *ReadmeFeature) GetId() *FeatureId {
	if r == nil {
		return nil
	}
	return r.Id
}

func (r *ReadmeFeature) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *ReadmeFeature) GetAddendum() *string {
	if r == nil {
		return nil
	}
	return r.Addendum
}

func (r *ReadmeFeature) GetAdvanced() *bool {
	if r == nil {
		return nil
	}
	return r.Advanced
}

func (r *ReadmeFeature) GetSnippets() []*Snippet {
	if r == nil {
		return nil
	}
	return r.Snippets
}

func (r *ReadmeFeature) GetSnippetsAreOptional() bool {
	if r == nil {
		return false
	}
	return r.SnippetsAreOptional
}

func (r *ReadmeFeature) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *ReadmeFeature) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeFeature) SetId(id *FeatureId) {
	r.Id = id
	r.require(readmeFeatureFieldId)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeFeature) SetDescription(description *string) {
	r.Description = description
	r.require(readmeFeatureFieldDescription)
}

// SetAddendum sets the Addendum field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeFeature) SetAddendum(addendum *string) {
	r.Addendum = addendum
	r.require(readmeFeatureFieldAddendum)
}

// SetAdvanced sets the Advanced field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeFeature) SetAdvanced(advanced *bool) {
	r.Advanced = advanced
	r.require(readmeFeatureFieldAdvanced)
}

// SetSnippets sets the Snippets field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeFeature) SetSnippets(snippets []*Snippet) {
	r.Snippets = snippets
	r.require(readmeFeatureFieldSnippets)
}

// SetSnippetsAreOptional sets the SnippetsAreOptional field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *ReadmeFeature) SetSnippetsAreOptional(snippetsAreOptional bool) {
	r.SnippetsAreOptional = snippetsAreOptional
	r.require(readmeFeatureFieldSnippetsAreOptional)
}

func (r *ReadmeFeature) UnmarshalJSON(data []byte) error {
	type unmarshaler ReadmeFeature
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = ReadmeFeature(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *ReadmeFeature) MarshalJSON() ([]byte, error) {
	type embed ReadmeFeature
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *ReadmeFeature) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// The remote where the README.md is hosted.
type Remote struct {
	Type   string
	Github *GithubRemote
}

func (r *Remote) GetType() string {
	if r == nil {
		return ""
	}
	return r.Type
}

func (r *Remote) GetGithub() *GithubRemote {
	if r == nil {
		return nil
	}
	return r.Github
}

func (r *Remote) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	r.Type = unmarshaler.Type
	if unmarshaler.Type == "" {
		return fmt.Errorf("%T did not include discriminant type", r)
	}
	switch unmarshaler.Type {
	case "github":
		value := new(GithubRemote)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.Github = value
	}
	return nil
}

func (r Remote) MarshalJSON() ([]byte, error) {
	if err := r.validate(); err != nil {
		return nil, err
	}
	if r.Github != nil {
		return internal.MarshalJSONWithExtraProperty(r.Github, "type", "github")
	}
	return nil, fmt.Errorf("type %T does not define a non-empty union type", r)
}

type RemoteVisitor interface {
	VisitGithub(*GithubRemote) error
}

func (r *Remote) Accept(visitor RemoteVisitor) error {
	if r.Github != nil {
		return visitor.VisitGithub(r.Github)
	}
	return fmt.Errorf("type %T does not define a non-empty union type", r)
}

func (r *Remote) validate() error {
	if r == nil {
		return fmt.Errorf("type %T is nil", r)
	}
	var fields []string
	if r.Github != nil {
		fields = append(fields, "github")
	}
	if len(fields) == 0 {
		if r.Type != "" {
			return fmt.Errorf("type %T defines a discriminant set to %q but the field is not set", r, r.Type)
		}
		return fmt.Errorf("type %T is empty", r)
	}
	if len(fields) > 1 {
		return fmt.Errorf("type %T defines values for %s, but only one value is allowed", r, fields)
	}
	if r.Type != "" {
		field := fields[0]
		if r.Type != field {
			return fmt.Errorf(
				"type %T defines a discriminant set to %q, but it does not match the %T field; either remove or update the discriminant to match",
				r,
				r.Type,
				r,
			)
		}
	}
	return nil
}

var (
	rubyGemsPublishInfoFieldPackageName = big.NewInt(1 << 0)
)

type RubyGemsPublishInfo struct {
	PackageName string `json:"packageName" url:"packageName"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RubyGemsPublishInfo) GetPackageName() string {
	if r == nil {
		return ""
	}
	return r.PackageName
}

func (r *RubyGemsPublishInfo) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RubyGemsPublishInfo) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetPackageName sets the PackageName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RubyGemsPublishInfo) SetPackageName(packageName string) {
	r.PackageName = packageName
	r.require(rubyGemsPublishInfoFieldPackageName)
}

func (r *RubyGemsPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler RubyGemsPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RubyGemsPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RubyGemsPublishInfo) MarshalJSON() ([]byte, error) {
	type embed RubyGemsPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RubyGemsPublishInfo) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	rubyInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type RubyInfo struct {
	PublishInfo *RubyGemsPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RubyInfo) GetPublishInfo() *RubyGemsPublishInfo {
	if r == nil {
		return nil
	}
	return r.PublishInfo
}

func (r *RubyInfo) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RubyInfo) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RubyInfo) SetPublishInfo(publishInfo *RubyGemsPublishInfo) {
	r.PublishInfo = publishInfo
	r.require(rubyInfoFieldPublishInfo)
}

func (r *RubyInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler RubyInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RubyInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RubyInfo) MarshalJSON() ([]byte, error) {
	type embed RubyInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RubyInfo) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	rustInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type RustInfo struct {
	PublishInfo *CargoPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RustInfo) GetPublishInfo() *CargoPublishInfo {
	if r == nil {
		return nil
	}
	return r.PublishInfo
}

func (r *RustInfo) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RustInfo) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RustInfo) SetPublishInfo(publishInfo *CargoPublishInfo) {
	r.PublishInfo = publishInfo
	r.require(rustInfoFieldPublishInfo)
}

func (r *RustInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler RustInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RustInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RustInfo) MarshalJSON() ([]byte, error) {
	type embed RustInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RustInfo) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// A snippet that can be either a plain string (treated as code in the generator's language),
// markdown content, or a code block with optional language override.
// Plain strings are supported for backwards compatibility.
type Snippet struct {
	String          string
	MarkdownSnippet *MarkdownSnippet
	CodeSnippet     *CodeSnippet

	typ string
}

func (s *Snippet) GetString() string {
	if s == nil {
		return ""
	}
	return s.String
}

func (s *Snippet) GetMarkdownSnippet() *MarkdownSnippet {
	if s == nil {
		return nil
	}
	return s.MarkdownSnippet
}

func (s *Snippet) GetCodeSnippet() *CodeSnippet {
	if s == nil {
		return nil
	}
	return s.CodeSnippet
}

func (s *Snippet) UnmarshalJSON(data []byte) error {
	var valueString string
	if err := json.Unmarshal(data, &valueString); err == nil {
		s.typ = "String"
		s.String = valueString
		return nil
	}
	valueMarkdownSnippet := new(MarkdownSnippet)
	if err := json.Unmarshal(data, &valueMarkdownSnippet); err == nil {
		s.typ = "MarkdownSnippet"
		s.MarkdownSnippet = valueMarkdownSnippet
		return nil
	}
	valueCodeSnippet := new(CodeSnippet)
	if err := json.Unmarshal(data, &valueCodeSnippet); err == nil {
		s.typ = "CodeSnippet"
		s.CodeSnippet = valueCodeSnippet
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, s)
}

func (s Snippet) MarshalJSON() ([]byte, error) {
	if s.typ == "String" || s.String != "" {
		return json.Marshal(s.String)
	}
	if s.typ == "MarkdownSnippet" || s.MarkdownSnippet != nil {
		return json.Marshal(s.MarkdownSnippet)
	}
	if s.typ == "CodeSnippet" || s.CodeSnippet != nil {
		return json.Marshal(s.CodeSnippet)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", s)
}

type SnippetVisitor interface {
	VisitString(string) error
	VisitMarkdownSnippet(*MarkdownSnippet) error
	VisitCodeSnippet(*CodeSnippet) error
}

func (s *Snippet) Accept(visitor SnippetVisitor) error {
	if s.typ == "String" || s.String != "" {
		return visitor.VisitString(s.String)
	}
	if s.typ == "MarkdownSnippet" || s.MarkdownSnippet != nil {
		return visitor.VisitMarkdownSnippet(s.MarkdownSnippet)
	}
	if s.typ == "CodeSnippet" || s.CodeSnippet != nil {
		return visitor.VisitCodeSnippet(s.CodeSnippet)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", s)
}

var (
	swiftInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type SwiftInfo struct {
	PublishInfo *SwiftPackageManagerPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SwiftInfo) GetPublishInfo() *SwiftPackageManagerPublishInfo {
	if s == nil {
		return nil
	}
	return s.PublishInfo
}

func (s *SwiftInfo) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SwiftInfo) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SwiftInfo) SetPublishInfo(publishInfo *SwiftPackageManagerPublishInfo) {
	s.PublishInfo = publishInfo
	s.require(swiftInfoFieldPublishInfo)
}

func (s *SwiftInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler SwiftInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SwiftInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SwiftInfo) MarshalJSON() ([]byte, error) {
	type embed SwiftInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SwiftInfo) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	swiftPackageManagerPublishInfoFieldGitUrl     = big.NewInt(1 << 0)
	swiftPackageManagerPublishInfoFieldMinVersion = big.NewInt(1 << 1)
)

type SwiftPackageManagerPublishInfo struct {
	GitUrl     string `json:"gitUrl" url:"gitUrl"`
	MinVersion string `json:"minVersion" url:"minVersion"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SwiftPackageManagerPublishInfo) GetGitUrl() string {
	if s == nil {
		return ""
	}
	return s.GitUrl
}

func (s *SwiftPackageManagerPublishInfo) GetMinVersion() string {
	if s == nil {
		return ""
	}
	return s.MinVersion
}

func (s *SwiftPackageManagerPublishInfo) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SwiftPackageManagerPublishInfo) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetGitUrl sets the GitUrl field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SwiftPackageManagerPublishInfo) SetGitUrl(gitUrl string) {
	s.GitUrl = gitUrl
	s.require(swiftPackageManagerPublishInfoFieldGitUrl)
}

// SetMinVersion sets the MinVersion field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SwiftPackageManagerPublishInfo) SetMinVersion(minVersion string) {
	s.MinVersion = minVersion
	s.require(swiftPackageManagerPublishInfoFieldMinVersion)
}

func (s *SwiftPackageManagerPublishInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler SwiftPackageManagerPublishInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SwiftPackageManagerPublishInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SwiftPackageManagerPublishInfo) MarshalJSON() ([]byte, error) {
	type embed SwiftPackageManagerPublishInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SwiftPackageManagerPublishInfo) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

var (
	typescriptInfoFieldPublishInfo = big.NewInt(1 << 0)
)

type TypescriptInfo struct {
	PublishInfo *NpmPublishInfo `json:"publishInfo,omitempty" url:"publishInfo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TypescriptInfo) GetPublishInfo() *NpmPublishInfo {
	if t == nil {
		return nil
	}
	return t.PublishInfo
}

func (t *TypescriptInfo) GetExtraProperties() map[string]interface{} {
	if t == nil {
		return nil
	}
	return t.extraProperties
}

func (t *TypescriptInfo) require(field *big.Int) {
	if t.explicitFields == nil {
		t.explicitFields = big.NewInt(0)
	}
	t.explicitFields.Or(t.explicitFields, field)
}

// SetPublishInfo sets the PublishInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (t *TypescriptInfo) SetPublishInfo(publishInfo *NpmPublishInfo) {
	t.PublishInfo = publishInfo
	t.require(typescriptInfoFieldPublishInfo)
}

func (t *TypescriptInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler TypescriptInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TypescriptInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TypescriptInfo) MarshalJSON() ([]byte, error) {
	type embed TypescriptInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*t),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, t.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (t *TypescriptInfo) String() string {
	if t == nil {
		return "<nil>"
	}
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}
